# Generated by Django 4.2.27 on 2025-12-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=10)),
                ('parent', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('legend', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=10)),
                ('object', models.CharField(max_length=100)),
                ('svg', models.ImageField(upload_to='components/')),
                ('png', models.ImageField(upload_to='components/')),
                ('grips', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
